name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main ./cmd/api/main.go
