name: Build and Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main main.go

      - name: Zip build
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./lambda.zip . -i main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var "lambda_zip_file=$GITHUB_WORKSPACE/lambda.zip"
        working-directory: ./terraform
